---
# Server Configuration
# Note: ip_address will be prompted interactively at runtime
# (override with -e "ip_address=x.x.x.x" to skip prompt)
# ip_address: will be prompted
added_user: organic
user_password: "{{ lookup('file', lookup('env','HOME') + '/.ssh/password') }}"
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_gitlab.pub') }}"

# System Packages
sys_packages:
  - curl
  - vim
  - git
  - ufw
  - htop
  - tmux
  - zip
  - unzip
  - build-essential

# Timezone Configuration
system_timezone: America/Los_Angeles

# Security Configuration
ssh_port: 22
disable_root_login: true  # CHANGED: Should be true for production
password_authentication: false  # CHANGED: Should be false, use SSH keys only

# Firewall Configuration
ufw_allowed_ports:
  - port: "{{ ssh_port }}"
    proto: tcp
  - port: 80
    proto: tcp
  - port: 443
    proto: tcp

# Fail2ban Configuration (Intelligent Intrusion Prevention)
address: 127.0.0.1 {{ ip_address }}
fail2ban_ssh_service_name: sshd
fail2ban_bantime: 86400        # 24 hours (86400 seconds)
fail2ban_findtime: 600         # 10 minutes (600 seconds)
fail2ban_maxretry: 3           # Maximum 3 failed attempts
# Fail2ban uses intelligent multi-tier protection:
# - SSH protection with aggressive detection
# - Recidive jail: bans repeat offenders for 1 week (3+ bans) or 30 days (5+ bans)
# - Web server protection: nginx/apache against bots, scripts, proxies
# - PHP injection protection
# - Port scanning detection
# - PAM and sudo authentication monitoring
# Enable service-specific jails in roles/security/templates/jail.local.j2

# Docker Configuration
install_docker: true
docker_compose_version: "latest"
docker_users:
  - "{{ added_user }}"

# LEMP Stack Configuration
install_lemp: false  # Set to true to install Nginx, MySQL, PHP
php_modules:
  - php-fpm
  - php-mysql
  - php-curl
  - php-gd
  - php-intl
  - php-mbstring
  - php-soap
  - php-xml
  - php-xmlrpc
  - php-zip

# Swap Configuration
enable_swap: true  # Automatically sizes swap based on RAM

# Cron Jobs Configuration
enable_cron_jobs: true
enable_unattended_upgrades: true
enable_auto_updates: true
enable_periodic_reboot: false  # WARNING: Reboots server every 6 hours if enabled!

# Development Tools Configuration
install_dev_tools: true  # Set to true to install Neovim, Node.js, etc.
install_neovim: true
install_nodejs: true
install_claude_code: true
nodejs_version: "22"

# Monitoring Setup
install_monitoring: false  # Set to true to enable monitoring tools

# WordPress Configuration
install_wordpress: false  # Set to true to deploy WordPress (requires LEMP stack)
configure_nginx_vhost: false  # Set to true to configure Nginx virtual host
full_domain: example.com  # CHANGE THIS: Your domain name (e.g., example.com)
http_host: "{{ full_domain }}"  # HTTP host (usually same as full_domain)
# WordPress database settings (override in vault.yml):
# mysql_db: wordpress_db
# mysql_user: wordpress_user
# mysql_password: <secure_password_from_vault>
# mysql_root_password: <secure_password_from_vault>

# Certbot SSL/TLS Configuration
install_certbot: false  # Set to true to install SSL certificates
certbot_email: admin@example.com  # CHANGE THIS: Your email for Let's Encrypt notifications
certbot_www_domain: false  # Include www subdomain in certificate
certbot_auto_renew: false  # Enable automatic renewal (recommended)

# Debug/Testing
ansible_check_mode: false

# =============================================================================
# ADVANCED SECURITY CONFIGURATION
# =============================================================================

# Kernel Hardening (sysctl)
enable_kernel_hardening: false  # Enable via interactive prompt or set to true
kernel_hardening_settings:
  # Network Security
  net.ipv4.ip_forward: 0  # Disable IP forwarding (overridden to 1 when Docker is enabled)
  net.ipv4.conf.all.send_redirects: 0  # Disable ICMP redirects
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0  # Don't accept ICMP redirects
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.secure_redirects: 0
  net.ipv4.conf.default.secure_redirects: 0
  net.ipv6.conf.all.accept_redirects: 0
  net.ipv6.conf.default.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0  # Don't accept source routing
  net.ipv4.conf.default.accept_source_route: 0
  net.ipv6.conf.all.accept_source_route: 0
  net.ipv6.conf.default.accept_source_route: 0
  net.ipv4.tcp_syncookies: 1  # Enable SYN cookies (SYN flood protection)
  net.ipv4.icmp_echo_ignore_broadcasts: 1  # Ignore ping broadcasts
  net.ipv4.icmp_ignore_bogus_error_responses: 1  # Ignore bogus ICMP responses
  net.ipv4.conf.all.log_martians: 1  # Log martian packets
  net.ipv4.conf.default.log_martians: 1
  net.ipv4.conf.all.rp_filter: 1  # Enable reverse path filtering
  net.ipv4.conf.default.rp_filter: 1
  # Kernel Security
  kernel.dmesg_restrict: 1  # Restrict dmesg access
  kernel.kptr_restrict: 2  # Hide kernel pointers
  kernel.yama.ptrace_scope: 1  # Restrict ptrace

# AppArmor Enforcement
enable_apparmor: false  # Enable via interactive prompt or set to true
apparmor_enforce_mode: true  # true = enforce, false = complain

# Secure Shared Memory
enable_secure_shm: false  # Enable via interactive prompt or set to true

# Lynis Security Auditing
enable_lynis: false  # Enable via interactive prompt or set to true
lynis_run_audit: false  # Run audit during provisioning (takes time)
lynis_email_report: ""  # Email address for audit reports (leave empty to disable)

# Rootkit Detection (rkhunter)
enable_rkhunter: false  # Enable via interactive prompt or set to true
rkhunter_cron_daily: true
rkhunter_email: ""  # Email for alerts (leave empty to disable)

# File Integrity Monitoring (AIDE)
enable_aide: false  # Enable via interactive prompt or set to true
aide_cron_daily: true
aide_email: ""  # Email for alerts (leave empty to disable)

# Audit Logging (auditd)
enable_auditd: false  # Enable via interactive prompt or set to true
auditd_rules:
  - "-w /etc/passwd -p wa -k passwd_changes"
  - "-w /etc/group -p wa -k group_changes"
  - "-w /etc/shadow -p wa -k shadow_changes"
  - "-w /etc/sudoers -p wa -k sudoers_changes"
  - "-w /var/log/auth.log -p wa -k auth_log_changes"
  - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time_change"
  - "-a always,exit -F arch=b64 -S sethostname -S setdomainname -k network_modifications"

# Log Monitoring (Logwatch)
enable_logwatch: false  # Enable via interactive prompt or set to true
logwatch_email: ""  # Email for daily reports (leave empty to disable)
logwatch_detail: "Med"  # Low, Med, High

# IPv6 Configuration
disable_ipv6: false  # Disabled by default, enable via advanced security

# Two-Factor Authentication (SSH)
enable_ssh_2fa: false  # REQUIRES MANUAL CONFIGURATION POST-INSTALL
ssh_2fa_grace_period: 30  # Seconds to allow key-only auth before requiring OTP

# Automated Backups
enable_backups: false  # Enable via interactive prompt or set to true
backup_destination: "/backup"  # Local backup directory
backup_retention_days: 7  # Days to keep backups
backup_schedule: "0 2 * * *"  # Cron schedule (default: 2 AM daily)
backup_mysql: false  # Backup MySQL databases
backup_directories:
  - /etc
  - /home
  - /var/www

# USB/Removable Media Restrictions
enable_usb_restrictions: false  # Enable via interactive prompt or set to true
usb_storage_blacklist: true

# Network Intrusion Detection (Suricata)
enable_suricata: false  # Enable via interactive prompt or set to true
suricata_interface: "eth0"  # Network interface to monitor
suricata_ruleset: "emerging-threats"  # emerging-threats, etpro, or custom


